// Catálogo de serviços organizado por categoria.
// Cada categoria tem um ícone (emoji), título e lista de serviços selecionáveis.

export const CATEGORIES = [
  {
    id: 'suporte-ti',
    icon: '🖥️',
    title: 'Suporte de TI',
    services: [
      'Formatação de computadores',
      'Instalação de Windows/Linux',
      'Instalação de programas',
      'Configuração de impressoras',
      'Configuração de Wi-Fi e roteadores',
      'Backup e recuperação de dados',
      'Otimização e limpeza preventiva',
      'Upgrade de SSD/RAM',
      'Suporte remoto',
      'Suporte para empresas (servidores, AD, M365)',
      'E-mail corporativo e backup empresarial',
      'Antivírus/EDR',
      'Help Desk',
    ],
  },
  {
    id: 'redes-infra',
    icon: '🌐',
    title: 'Redes e Infraestrutura',
    services: [
      'Cabeamento estruturado (Cat6/Cat6A)',
      'Fibra óptica interna',
      'Switches, roteadores e VLAN',
      'Firewall e VPN',
      'Wi-Fi corporativo e Mesh',
      'Redes para condomínios',
      'Organização de rack e patch panel',
      'Nobreak e PDU',
      'Sala técnica / Data Center',
    ],
  },
  {
    id: 'telecom',
    icon: '📡',
    title: 'Telecomunicações',
    services: [
      'FTTH / FTTB / FTTx',
      'Fusão de fibra óptica',
      'OTDR e Power Meter (certificação)',
      'Manutenção e expansão de rede óptica',
      'GPON, OLT, ONU/ONT',
      'Splitters e CTO',
      'Diagnóstico de problemas ópticos',
    ],
  },
  {
    id: 'seguranca',
    icon: '📹',
    title: 'Segurança Eletrônica',
    services: [
      'Câmeras IP / Wi-Fi / PoE',
      'DVR e NVR',
      'Monitoramento remoto pelo celular',
      'Alarmes e sensores',
      'Controle de acesso e biometria',
      'Interfone e vídeo porteiro',
      'Fechaduras eletrônicas',
    ],
  },
  {
    id: 'automacao',
    icon: '🚪',
    title: 'Automação',
    services: [
      'Automação de portões',
      'Fechaduras e controle remoto',
      'Leitores biométricos e RFID',
      'Automação residencial (luz, tomadas, ar-condicionado)',
      'Automação por aplicativo/voz',
      'Automação empresarial de acesso',
      'IoT e sensores de presença',
    ],
  },
  {
    id: 'software',
    icon: '💻',
    title: 'Desenvolvimento de Sistemas',
    services: [
      'Sites institucionais e landing pages',
      'E-commerce e portais',
      'Sistemas empresariais (estoque, financeiro)',
      'CRM e agendamento',
      'Help Desk e controle de ativos',
      'Integrações e SaaS',
    ],
  },
  {
    id: 'projetos',
    icon: '🧠',
    title: 'Projetos e Consultoria',
    services: [
      'Projeto completo de TI (levantamento a entrega)',
      'Diagrama lógico e físico de rede',
      'Projeto de rack e cabeamento',
      'Lista de materiais e memorial descritivo',
      'Documentação técnica',
      'Laudo/relatório de inspeção',
    ],
  },
  {
    id: 'ciberseguranca',
    icon: '🛡️',
    title: 'Cibersegurança',
    services: [
      'Firewall, VPN e segmentação (VLAN)',
      'Backup e controle de acesso',
      'Antivírus/EDR e MFA',
      'Políticas de senha e atualizações',
      'Pentest autorizado / Vulnerability Assessment',
      'Hardening e monitoramento (SIEM/SOC)',
    ],
  },
  {
    id: 'cloud',
    icon: '☁️',
    title: 'Cloud',
    services: [
      'AWS (EC2, S3, VPC, IAM, RDS)',
      'Servidores VPS Linux/Windows',
      'Virtualização (Proxmox, Hyper-V, VMware)',
      'Docker, Nginx, Apache',
      'Backup e monitoramento em nuvem',
    ],
  },
  {
    id: 'impressoras',
    icon: '🖨️',
    title: 'Impressoras e Periféricos',
    services: [
      'Impressoras térmicas e Zebra',
      'Scanners e coletores',
      'Configuração de impressão em rede',
      'Controle de suprimentos',
    ],
  },
  {
    id: 'energia-solar',
    icon: '☀️',
    title: 'Energia Solar',
    services: [
      'Instalação de placas solares (on-grid)',
      'Instalação de placas solares (off-grid/híbrido)',
      'Dimensionamento de sistema fotovoltaico',
      'Instalação de inversor solar',
      'Fixação e estruturas de suporte (telhado/solo)',
      'Manutenção preventiva de painéis solares',
      'Limpeza de painéis solares',
      'Manutenção corretiva e diagnóstico de falhas',
      'Monitoramento de geração de energia',
      'Troca de inversor/componentes',
      'Projeto e homologação junto à concessionária',
    ],
  },
  {
    id: 'eletrica',
    icon: '⚡',
    title: 'Elétrica',
    services: [
      'Tomadas, interruptores e luminárias',
      'Quadros elétricos e disjuntores',
      'Infraestrutura elétrica para TI e racks',
      'Nobreaks, DPS e DR',
      'Projeto elétrico e diagrama unifilar',
      'Infraestrutura elétrica para CFTV/automação',
    ],
  },
]
